# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastmigrate',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastmigrate',
                'lib_path': 'fastmigrate'},
  'syms': {'fastmigrate.core': {'fastmigrate.core.foo': ('core.html#foo', 'fastmigrate/core.py')}}}
